/**
 * Global Constants
 */

export const CONSTANTS = {
  TICK_INTERVAL_MS: 600_000,
  SNAPSHOT_INTERVAL_MS: 3_600_000,
  CSV_EXPORT_INTERVAL_MS: 86_400_000,

  DEATH_BALANCE_THRESHOLD: 0.01,
  BREEDING_BALANCE_THRESHOLD: 5.0,
  BREEDING_COST_PER_PARENT: 2.0,
  OFFSPRING_INITIAL_BALANCE: 3.0,
  EMERGENCY_BALANCE_THRESHOLD: 2.0,

  NEONATE_DURATION: 50,
  JUVENILE_DURATION: 150,
  MINIMUM_BREEDING_AGE: 200,
  BREEDING_COOLDOWN: 50,

  INITIAL_GENE_COUNT: 63,
  MAX_GENE_COUNT: 200,
  MIN_GENE_COUNT: 20,

  BASE_MUTATION_RATE: 0.02,
  BASE_DUPLICATION_RATE: 0.01,
  BASE_DELETION_RATE: 0.01,
  BASE_HGT_RATE: 0.001,
  BASE_DE_NOVO_RATE: 0.001,
} as const;

export type ConstantKey = keyof typeof CONSTANTS;
